# Generated by Django 5.2.9 on 2025-12-02 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventario', models.CharField(max_length=50, unique=True, verbose_name='Número de Inventario')),
                ('descripcion', models.TextField(verbose_name='Descripción o Nombre del Equipo')),
                ('precio_adquisicion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Adquisición')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Equipo de Inventario',
                'verbose_name_plural': 'Equipos de Inventario',
                'ordering': ['numero_inventario'],
            },
        ),
    ]
