# Generated by Django 5.2.8 on 2025-12-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='user',
        ),
        migrations.AddField(
            model_name='docente',
            name='apellido',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='nombre',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
